repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/python/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear>=21.4.3]
- repo: https://github.com/jazzband/pip-tools
  rev: 6.4.0
  hooks:
    - id: pip-compile
      name: pip-compile setup.py
      args: [setup.py, --output-file=requirements/install.txt]
      files: ^(setup\.py|requirements\/install\.txt)$
    - id: pip-compile
      name: pip-compile requirements/dev.in
      args: [requirements/dev.in]
      files: ^requirements\/(tests|dev)\.(in|txt)$
    - id: pip-compile
      name: pip-compile requirements/tests.in
      args: [requirements/tests.in]
      files: ^requirements\/tests\.(in|txt)$
