ci:
  skip: [pip-compile]

repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
  hooks:
  - id: pyupgrade
    args: [--py39-plus]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==23.5.9]
- repo: https://github.com/jazzband/pip-tools
  rev: 7.3.0
  hooks:
    - id: pip-compile
      name: pip-compile setup.py
      args: [setup.py, --output-file=requirements/install.txt]
      files: ^(setup\.py|requirements\/install\.txt)$
    - id: pip-compile
      name: pip-compile requirements/dev.in
      args: [requirements/dev.in]
      files: ^requirements\/(tests|dev)\.(in|txt)$
    - id: pip-compile
      name: pip-compile requirements/tests.in
      args: [requirements/tests.in]
      files: ^requirements\/tests\.(in|txt)$
    - id: pip-compile
      name: pip-compile requirements/install-min.in
      args: [requirements/install-min.in]
      files: ^requirements\/install-min\.(in|txt)$
