"""v0.15

Revision ID: 0.15
Revises: 0.14
Create Date: 2023-05-05 17:52:30.721451

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0.15"
down_revision = "0.14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "st_dl_weather_fcast_data_by_site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_st_dl_weather_fcast_data_by_site_site_id_sites"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_st_dl_weather_fcast_data_by_site")),
        sa.UniqueConstraint(
            "site_id", name=op.f("uq_st_dl_weather_fcast_data_by_site_site_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("st_dl_weather_fcast_data_by_site")
    # ### end Alembic commands ###
