name: build
on:
  push:
    branches: ["master"]
    tags: ["*"]
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox
      - run: tox -elint
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: '3.11', python: '3.11', tox: py311}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run:
          sudo sh -c "echo 'deb https://packagecloud.io/timescale/timescaledb/ubuntu/
          `lsb_release -c -s` main' > /etc/apt/sources.list.d/timescaledb.list"
      - run:
          wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey |
          sudo apt-key add -
      - run: sudo apt-get update
      - run: sudo apt-get install timescaledb-2-postgresql-14
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox codecov
      - run: tox -e${{ matrix.tox }}
      - run: codecov
  release:
    needs: [lint, tests]
    name: PyPI release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip wheel
      - run: pip install twine
      - run: python setup.py sdist bdist_wheel
      - run: twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
