name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox
      - run: tox -elint
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.7', python: '3.7', os: ubuntu-latest, tox: py37}
          - {name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run:
          sudo sh -c "echo 'deb https://packagecloud.io/timescale/timescaledb/ubuntu/
          `lsb_release -c -s` main' > /etc/apt/sources.list.d/timescaledb.list"
      - run:
          wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey |
          sudo apt-key add -
      - run: sudo apt-get update
      - run: sudo apt-get install timescaledb-2-postgresql-14
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox codecov
      - run: tox -e${{ matrix.tox }}
      - run: codecov
